backend:
  name: git-gateway
  branch: main

media_folder: "media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "news"
    label: "Blog Posts"
    folder: "news"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
